# Generated by Django 5.0.9 on 2024-10-18 15:43

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=50, verbose_name='Titel eingeben')),
                ('background_color', colorfield.fields.ColorField(choices=[('#000000', 'Black'), ('#FFFFFF', 'White')], default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Farbe auswählen')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
