# Generated by Django 5.0.9 on 2024-10-18 19:51

import colorfield.fields
import django.db.models.deletion
import djangocms_text.fields
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('cmsplugins', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', djangocms_text.fields.HTMLField(blank=True)),
                ('background_color', colorfield.fields.ColorField(choices=[('#000000', 'Black'), ('#FFFFFF', 'White')], default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Hintergrundfarbe auswählen')),
                ('image', filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
