# Generated by Django 5.0.9 on 2024-10-21 16:09

import django.db.models.deletion
import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('cmsplugins', '0002_aboutmemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSkillsmodel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', djangocms_text.fields.HTMLField(blank=True, null=True)),
                ('icon_url', models.URLField(verbose_name='Icon Urleinfügen')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
